spring:
  datasource:
    druid:
      url: jdbc:mysql://47.105.97.16:3306/colors_auth?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: root
      password: root
  redis:
    host: 47.105.97.16
    port: 6389
    password: liweichao
    database: 1

# redis client 的一种，性能据说强于 jedis .
#redisson:
#  config: classpath:single-server.yml