
   CREATE TABLE `account` (
      `id` BIGINT (20) UNSIGNED  NOT NULL AUTO_INCREMENT COMMENT '主键，钱包账户ID',
      `merchant_id` INT NOT NULL COMMENT '商家ID',
      `name` VARCHAR (100) NOT NULL COMMENT '账户名称',
      `mobile` VARCHAR (20) NOT NULL COMMENT '手机号',
      `type` INT NOT NULL DEFAULT 2 COMMENT '账户角色: 1:平台账户(AHS) 2:用户账户(SJ)',
      `default_payment_method` INT (11) NOT NULL DEFAULT '1' COMMENT '默认支付方式：1钱包余额 2富友金账户',
      `payment_methods` INT (11) NOT NULL DEFAULT '1' COMMENT '商家支持的支付方式(位表示)',
      `create_dt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
      `update_dt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
      `create_by` INT  NOT NULL DEFAULT 0  COMMENT '创建人',
      `update_by` INT  NOT NULL DEFAULT 0  COMMENT '修改人',
      `amount` DECIMAL (18, 3) NOT NULL DEFAULT 0 COMMENT '账户余额（包含冻结余额）',
      `amount_frozen` DECIMAL (18, 3) NOT NULL DEFAULT 0 COMMENT '冻结余额',
      `credit_limit` DECIMAL (18, 3) NOT NULL DEFAULT 0 COMMENT '信用额度，默认为0',
      `is_credit` INT NOT NULL DEFAULT 0 COMMENT '信用额度是否可用，1：可用，0：不可用。默认为0',
      `status` INT NOT NULL DEFAULT 1 COMMENT '账户状态 0,无效（冻结），1，有效',
      `comment` VARCHAR (255) NULL COMMENT '备注',
      `is_delete` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '删除状态： 0,未删除，1，已删除',
      PRIMARY KEY (`id`),
      KEY `idx_name` (`name`) USING BTREE,
      KEY `idx_create_time` (`create_dt`) USING BTREE,
      KEY `idx_merchant_id` (`merchant_id`) USING BTREE,
      KEY `idx_mobile` (`mobile`) USING BTREE
    )  AUTO_INCREMENT=10001 COMMENT = '钱包账户';
    CREATE TABLE `account_transaction` (
      `id` BIGINT (20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
      `account_id` BIGINT (20) NOT NULL COMMENT '账户id',
      `type` INT (11) NOT NULL COMMENT '交易类型：0：其他、1：商家充值、2：商家提现、3：买家结算单支付、4：卖家结算支付、5：结算单列表退款（未发货退款）、6：结算单明细退款（退货退款）、7：商家返利、8：商家罚款、9：绿色通道退款、10, 买家结算更换支付申请记录(支付失败重试)、11, ahs支付入账、12, 买家结算支付超时(查询支付状态)',
      `pay_method` INT (11) NOT NULL DEFAULT 1 COMMENT '支付方式/交易账户（默认为钱包账户，其他有支付方式的，支出账户为相对应的方式）',
      `transaction_id` VARCHAR (40) NOT NULL COMMENT '交易号，与子表中的字段对应',
      `transaction_amount` DECIMAL (18, 3) NOT NULL DEFAULT '0.000' COMMENT '条目的金额',
      `amount` DECIMAL (18, 3) NOT NULL DEFAULT '0.000' COMMENT '钱包账户余额变动金额',
      `amount_before` DECIMAL (18, 3) NOT NULL COMMENT '交易前钱包账户余额',
      `amount_after` DECIMAL (18, 3) NOT NULL COMMENT '交易后钱包账户余额',
      `create_user_id` BIGINT (20) NOT NULL DEFAULT 0 COMMENT '操作人id',
      `create_dt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
      `update_dt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
      `content` VARCHAR (255) DEFAULT NULL COMMENT '内容，可以直接展示到前端',
      `comment` VARCHAR (255) DEFAULT NULL COMMENT '备注',
      `detail_id` VARCHAR (100) NOT NULL DEFAULT '' COMMENT '详单号，若有则由调用方传入',
      `is_delete` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '删除状态： 0,未删除，1，已删除',
      `supply_order_no` varchar(32) DEFAULT NULL COMMENT '代拍单号，若有则由调用方传入',
      PRIMARY KEY (`id`),
      UNIQUE KEY `uniq_transaction_id` (`transaction_id`),
      KEY `idx_create_time` (`create_dt`) USING BTREE,
      KEY `idx_account_id` (`account_id`),
      KEY `idx_detail_id` (`detail_id`)
    ) COMMENT = '钱包账户流水';
    CREATE TABLE `account_payment_info` (
      `id` BIGINT (20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
      `account_id` BIGINT (20) NOT NULL COMMENT '账户id',
      `user_name` VARCHAR (45) NOT NULL COMMENT '用户姓名',
      `id_card` VARCHAR (45) NOT NULL COMMENT '身份证号',
      `mobile` VARCHAR (20) NOT NULL COMMENT '手机号',
      `account_name` VARCHAR (100) NOT NULL COMMENT '关联商户名称',
      `account_type` INT NOT NULL COMMENT '关联商户类型：1，银行卡，2，富友个人账户，3，富友企业账户',
      `account_no` VARCHAR (100) NOT NULL COMMENT '关联商户号码',
      `bank_name` VARCHAR (45) NOT NULL COMMENT '开户行',
      `bank_account` VARCHAR (45) NOT NULL COMMENT '银行账户',
      `create_dt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
      `update_dt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
      `status` INT NOT NULL COMMENT '状态 0,无效，1，有效',
      `comment` VARCHAR (200) NULL COMMENT '备注',
      `sign_status` INT (11) NOT NULL DEFAULT '0' COMMENT '快速支付签约状态  0：未签约   1：已签约',
      `is_delete` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '删除状态： 0,未删除，1，已删除',
      PRIMARY KEY (`id`),
      KEY `idx_create_time` (`create_dt`) USING BTREE,
      KEY `idx_account_id` (`account_id`) USING BTREE,
      KEY `idx_id_card` (`id_card`) USING BTREE,
      KEY `idx_mobile` (`mobile`) USING BTREE
    ) COMMENT = '钱包账户所关联的支付信息';
    CREATE TABLE `account_recharge` (
      `id` BIGINT (20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
      `account_id` BIGINT (20) NOT NULL COMMENT '账户id',
      `transaction_id` VARCHAR (40) NOT NULL COMMENT '充值到爱回收账号的第三方详单号',
      `detail_id` VARCHAR (100) NOT NULL COMMENT '详单号，若有则由调用方传入,对于老的富友充值方式，由调用方传进来，其他为钱包服务生成',
      `amount` DECIMAL (18, 3) NOT NULL COMMENT '充值金额',
      `status` INT NOT NULL COMMENT '状态 1:充值中 0:充值失败 2:充值成功',
      `completed_at` DATETIME NOT NULL COMMENT '充值完成时间',
      `mobile` VARCHAR (20) NOT NULL COMMENT '充值手机号',
      `type` INT NOT NULL DEFAULT 0 COMMENT '充值方式：1：富友转账充值（充值码），2：富友金账户转账',
      `create_dt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
      `update_dt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
      `content` VARCHAR (255) NULL COMMENT '内容',
      `comment` VARCHAR (255) NULL COMMENT '备注',
      `is_delete` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '删除状态： 0,未删除，1，已删除',
      PRIMARY KEY (`id`),
      UNIQUE KEY `uniq_transaction_id` (`transaction_id`),
      UNIQUE KEY `uniq_detail_id` (`detail_id`),
      KEY `idx_create_time` (`create_dt`) USING BTREE,
      KEY `idx_account_id` (`account_id`) USING BTREE
    ) COMMENT = '钱包账户充值信息';
    CREATE TABLE `account_withdraw` (
      `id` BIGINT (20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
      `account_id` BIGINT (20) NOT NULL COMMENT '账户id',
      `transaction_id` VARCHAR (40) NOT NULL COMMENT '提现流水号（会传入第三方支付）',
      `mobile` VARCHAR (20) NOT NULL COMMENT '提现手机号',
      `amount` DECIMAL (18, 3) NOT NULL COMMENT '充值金额',
      `status` INT NOT NULL COMMENT '状态 1:提现中 0:提现失败 2:提现成功 3: ',
      `type` INT NOT NULL DEFAULT 0 COMMENT '提现方式：1: 富友金账户（转账到富友金账户）',
      `create_dt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
      `update_dt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
      `content` VARCHAR (255) NULL COMMENT '内容',
      `comment` VARCHAR (255) NULL COMMENT '备注',
      `is_delete` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '删除状态： 0,未删除，1，已删除',
      PRIMARY KEY (`id`),
      UNIQUE KEY `uniq_transaction_id` (`transaction_id`),
      KEY `idx_create_time` (`create_dt`) USING BTREE,
      KEY `idx_account_id` (`account_id`) USING BTREE,
      KEY `idx_mobile` (`mobile`) USING BTREE
    ) COMMENT = '提现记录';
    CREATE TABLE `account_pay` (
      `id` BIGINT (20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
      `account_id` BIGINT (20) NOT NULL COMMENT '账户id',
      `detail_id` VARCHAR (100) NOT NULL COMMENT '详单号，由调用方传入',
      `transaction_id` VARCHAR (40) NOT NULL COMMENT '钱包服务内部流水号',
      `business_type` INT (11) NOT NULL DEFAULT 0 COMMENT '业务类型（“买家结算”，“卖家结算”）',
      `pay_method` INT (11) NOT NULL DEFAULT 0 COMMENT '支付方式：1钱包余额 2富友金账户',
      `mobile` VARCHAR (20) NOT NULL COMMENT '手机号',
      `amount` DECIMAL (18, 3) NOT NULL COMMENT '金额',
      `status` INT (11) NOT NULL COMMENT '状态  0:支付失败， 1:支付中 2:支付成功',
      `create_user_id` bigint(20) NOT NULL DEFAULT 0 COMMENT '创建人id',
      `update_user_id` bigint(20) NOT NULL DEFAULT 0 COMMENT '更新人id',
      `create_dt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
      `update_dt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
      `content` VARCHAR (255) DEFAULT NULL COMMENT '内容',
      `comment` VARCHAR (255) DEFAULT NULL COMMENT '备注',
      `is_delete` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '删除状态： 0,未删除，1，已删除',
      PRIMARY KEY (`id`),
      UNIQUE KEY `uniq_transaction_id` (`transaction_id`),
      UNIQUE KEY `uniq_detail_id_and_business_type` (`detail_id`, `business_type`) USING BTREE,
      KEY `idx_create_time` (`create_dt`) USING BTREE,
      KEY `idx_account_id` (`account_id`) USING BTREE,
      KEY `idx_mobile` (`mobile`) USING BTREE
    ) COMMENT = '支付详情';
    CREATE TABLE `account_pay_fuiou` (
      `id` BIGINT (20) UNSIGNED NOT NULL COMMENT '主键，与account_pay的id相同',
      `account_id` BIGINT (20) NOT NULL COMMENT '账户id',
      `detail_id` VARCHAR (100) NOT NULL COMMENT '详单号，由调用方传入',
      `transaction_id` VARCHAR (40) NOT NULL COMMENT '钱包服务内部流水号',
      `business_type` INT (11) NOT NULL DEFAULT 0 COMMENT '业务类型（“买家结算”，“卖家结算”）',
      `mobile` VARCHAR (20) NOT NULL COMMENT '手机号',
      `amount` DECIMAL (18, 3) NOT NULL COMMENT '金额',
      `status` INT NOT NULL COMMENT '状态  0:支付失败， 1:支付中 2:支付成功',
      `create_user_id` bigint(20) NOT NULL DEFAULT 0 COMMENT '创建人id',
      `update_user_id` bigint(20) NOT NULL DEFAULT 0 COMMENT '更新人id',
      `create_dt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
      `update_dt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
      `content` VARCHAR (255) NULL COMMENT '内容',
      `comment` VARCHAR (255) NULL COMMENT '备注',
      `is_delete` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '删除状态： 0,未删除，1，已删除',
      PRIMARY KEY (`id`),
      UNIQUE KEY `uniq_transaction_id` (`transaction_id`),
      UNIQUE KEY `uniq_detail_id_and_business_type` (`detail_id`, `business_type`) USING BTREE,
      KEY `idx_create_time` (`create_dt`) USING BTREE,
      KEY `idx_account_id` (`account_id`) USING BTREE,
      KEY `idx_mobile` (`mobile`) USING BTREE
    ) COMMENT = '富友支付的详情';
    CREATE TABLE `account_operation_log` (
      `id` BIGINT (20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
      `account_id` BIGINT (20) NOT NULL COMMENT '账户id',
      `query_transaction_no` VARCHAR (40) DEFAULT NULL COMMENT '查询流水号',
      `type` INT NOT NULL DEFAULT 0 COMMENT '交易类型：0：其他、1：商家充值、2：商家提现、3：买家结算单支付、4：卖家结算支付、5：结算单列表退款（未发货退款）、6：结算单明细退款（退货退款）、7：商家返利、8：商家罚款、9：绿色通道退款',
      `create_dt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
      `content` VARCHAR (500) NULL COMMENT '内容',
      `is_delete` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '删除状态： 0,未删除，1，已删除',
      PRIMARY KEY (`id`),
      KEY `idx_create_time` (`create_dt`) USING BTREE,
      KEY `idx_account_id` (`account_id`) USING BTREE,
      KEY `idx_query_transaction_no` (`query_transaction_no`) USING BTREE
    ) COMMENT = '钱包账户操作日志';
    CREATE TABLE `account_refund` (
      `id` BIGINT (20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
      `account_id` BIGINT (20) NOT NULL COMMENT '账户id',
      `detail_id` VARCHAR (100) NOT NULL COMMENT '退款单号（结算单等），由调用方传入',
      `transaction_id` VARCHAR (40) NOT NULL COMMENT '退款流水号（会传入第三方支付）',
      `business_type` INT (11) NOT NULL DEFAULT 0 COMMENT '业务类型（1:未发货退款(结算单列表退款),2:退货退款(结算明细退款)，3：绿色通道退款）',
      `mobile` VARCHAR (20) NOT NULL COMMENT '退款手机号',
      `amount` DECIMAL (18, 3) NOT NULL COMMENT '退款金额',
      `status` INT NOT NULL COMMENT '状态 1:退款中 0:退款失败 2:退款成功 3: ',
      `type` INT NOT NULL DEFAULT 0 COMMENT '退款方式：1: 余额',
      `create_dt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
      `update_dt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
      `content` VARCHAR (255) NOT NULL DEFAULT '0' COMMENT '退款内容',
      `comment` VARCHAR (255) NULL COMMENT '备注',
      `is_delete` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '删除状态： 0,未删除，1，已删除',
      PRIMARY KEY (`id`),
      UNIQUE KEY `uniq_transaction_id` (`transaction_id`),
      UNIQUE KEY `uniq_record` (
        `detail_id`,
        `business_type`,
        `content`
      ),
      KEY `idx_create_time` (`create_dt`) USING BTREE
    ) COMMENT = '退款记录';
    CREATE TABLE `account_loan_repayment` (
      `id` BIGINT (20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
      `account_id` BIGINT (20) NOT NULL COMMENT '账户id',
      `detail_id` VARCHAR (100) NOT NULL COMMENT '业务单号（贷款,还款等），由调用方传入',
      `transaction_id` VARCHAR (40) NOT NULL COMMENT '流水号（会传入第三方支付）',
      `business_type` INT (11) NOT NULL DEFAULT '0' COMMENT '业务类型（1:卖家金融还款,2:卖家金融贷款）',
      `mobile` VARCHAR (20) NOT NULL COMMENT '手机号',
      `amount` DECIMAL (18, 3) NOT NULL COMMENT '金额',
      `status` INT (11) NOT NULL COMMENT '状态0:失败 2:成功',
      `pay_method` INT (11) NOT NULL DEFAULT '0' COMMENT '支付方式：1: 钱包余额',
      `create_user_id` BIGINT (20) NOT NULL DEFAULT '0' COMMENT '创建人id',
      `create_dt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
      `update_dt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
      `content` VARCHAR (255) DEFAULT '0' COMMENT '内容',
      `comment` VARCHAR (255) DEFAULT NULL COMMENT '备注',
      `is_delete` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '删除状态： 0,未删除，1，已删除',
      PRIMARY KEY (`id`) USING BTREE,
      UNIQUE KEY `uk_transaction_id` (`transaction_id`) USING BTREE,
      UNIQUE KEY `uk_record` (`detail_id`, `business_type`) USING BTREE,
      KEY `idx_create_time` (`create_dt`) USING BTREE
    ) COMMENT = '贷款还款记录';
    CREATE TABLE `transfer_result`  (
      `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
      `merchant_id` int(11) NOT NULL COMMENT '商家ID',
      `name` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '名称',
      `occurrenceTime` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP(0) COMMENT '迁移时间',
      `result` bit(1) NOT NULL COMMENT '迁移结果',
      `type` int(255) NOT NULL COMMENT '类型',
      `message` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '日志记录',
      `comment` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '备注',
      PRIMARY KEY (`id`) USING BTREE
      ) ENGINE = InnoDB AUTO_INCREMENT = 42904 CHARACTER SET = utf8 COLLATE = utf8_general_ci COMMENT = '迁移日志' ROW_FORMAT = Compact;
    CREATE TABLE `credit_account`  (
      `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
      `merchant_id` int(11) NOT NULL COMMENT '商家ID',
      `amount` decimal(18, 3) NOT NULL DEFAULT 0.000 COMMENT '账户余额（包含冻结余额）',
      `comment` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '备注',
      PRIMARY KEY (`id`) USING BTREE
    ) ENGINE = InnoDB AUTO_INCREMENT = 10068 CHARACTER SET = utf8 COLLATE = utf8_general_ci COMMENT = '保证金' ROW_FORMAT = Compact;